"""empty message

Revision ID: 54341c6f46e5
Revises: 5fd0470ffa9b
Create Date: 2020-04-30 16:33:25.135604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54341c6f46e5'
down_revision = '5fd0470ffa9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('n_title', sa.String(length=32), nullable=True),
    sa.Column('n_content', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
